### ISSUE TITLE
Consider making license more visible

### ISSUE THREAD

**Issue by matkoniecz** [fitnr/svgis#7]
I almost missed fact that this tool is GPLed ( https://github.com/fitnr/svgis/blob/master/src/svgis/graticule.py#L8 )

Can you consider mentioning it in README and/or adding LICENSE file? Note that it is recommended by GPL authors (though they suggest naming file COPYING - https://www.gnu.org/licenses/gpl-howto.en.html )

It would also allow GitHub to display license in project summary, see for example my https://github.com/matkoniecz/osm_bot_abstraction_layer

**Comment by fitnr** [comment]
added in 598c631744
